fix: fix Build Error Failed to compile
Next.js (14.2.5)
./src/design-system/component/TextInput/textInput.css.ts
NonErrorEmittedError: (Emitted value instead of an instance of Error) ReferenceError: $ is not defined  err