[#38] chore: introduce new script for sync design system (#39)
* chore: add test code

* chore: add svgr

* feat: add new script and add new folder for design system

* fix: fix diff

* fix: fix Build Error
Failed to compile

Next.js (14.2.5)
./src/design-system/component/TextInput/textInput.css.ts
NonErrorEmittedError: (Emitted value instead of an instance of Error) ReferenceError: $ is not defined  err

* chore: delete useless

* remove: 불필요한 코드 삭제

---------

Co-authored-by: SuJin <kimsujin001127@gmail.com>